version: "2.2"
services:
  mdns-reflector:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/yuxzhu/mdns-reflector:latest
    command: mdns-reflector -fnl info -- eth0 eth1
    network_mode: host
    restart: unless-stopped
